rm(list=ls())
library(gdalUtils)
library(raster)

basefolder<-"Z:/DATA_RAW/MERIT_Hydro/ADJUSTED_ELEVATION"
setwd(basefolder)
files<-list.files(basefolder, pattern ='*.tif$', all.files = TRUE, full.names =TRUE, recursive=TRUE)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_1.vrt")
gdalbuildvrt(files[1:300],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_2.vrt")
gdalbuildvrt(files[301:600],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_3.vrt")
gdalbuildvrt(files[601:900],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_4.vrt")
gdalbuildvrt(files[901:1150],outname)

rm(list=ls())
basefolder<-"Z:/DATA_RAW/MERIT_Hydro/ASPECT"
setwd(basefolder)
files<-list.files(basefolder, pattern ='*.tif$', all.files = TRUE, full.names =TRUE, recursive=TRUE)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_1.vrt")
gdalbuildvrt(files[1:300],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_2.vrt")
gdalbuildvrt(files[301:600],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_3.vrt")
gdalbuildvrt(files[601:900],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_4.vrt")
gdalbuildvrt(files[901:1150],outname)

rm(list=ls())
basefolder<-"Z:/DATA_RAW/MERIT_Hydro/FLOW_DIRECTION"
setwd(basefolder)
files<-list.files(basefolder, pattern ='*.tif$', all.files = TRUE, full.names =TRUE, recursive=TRUE)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_1.vrt")
gdalbuildvrt(files[1:300],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_2.vrt")
gdalbuildvrt(files[301:600],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_3.vrt")
gdalbuildvrt(files[601:900],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_4.vrt")
gdalbuildvrt(files[901:1150],outname)

rm(list=ls())
basefolder<-"Z:/DATA_RAW/MERIT_Hydro/HEIGHT_ABOVE_DRAINAGE"
setwd(basefolder)
files<-list.files(basefolder, pattern ='*.tif$', all.files = TRUE, full.names =TRUE, recursive=TRUE)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_1.vrt")
gdalbuildvrt(files[1:300],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_2.vrt")
gdalbuildvrt(files[301:600],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_3.vrt")
gdalbuildvrt(files[601:900],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_4.vrt")
gdalbuildvrt(files[901:1150],outname)

rm(list=ls())
basefolder<-"Z:/DATA_RAW/MERIT_Hydro/RIVER_WIDTH"
setwd(basefolder)
files<-list.files(basefolder, pattern ='*.tif$', all.files = TRUE, full.names =TRUE, recursive=TRUE)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_1.vrt")
gdalbuildvrt(files[1:300],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_2.vrt")
gdalbuildvrt(files[301:600],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_3.vrt")
gdalbuildvrt(files[601:900],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_4.vrt")
gdalbuildvrt(files[901:1150],outname)

rm(list=ls())
basefolder<-"Z:/DATA_RAW/MERIT_Hydro/SLOPE"
setwd(basefolder)
files<-list.files(basefolder, pattern ='*.tif$', all.files = TRUE, full.names =TRUE, recursive=TRUE)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_1.vrt")
gdalbuildvrt(files[1:300],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_2.vrt")
gdalbuildvrt(files[301:600],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_3.vrt")
gdalbuildvrt(files[601:900],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_4.vrt")
gdalbuildvrt(files[901:1150],outname)

rm(list=ls())
basefolder<-"Z:/DATA_RAW/MERIT_Hydro/TWI"
setwd(basefolder)
files<-list.files(basefolder, pattern ='*.tif$', all.files = TRUE, full.names =TRUE, recursive=TRUE)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_1.vrt")
gdalbuildvrt(files[1:300],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_2.vrt")
gdalbuildvrt(files[301:600],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_3.vrt")
gdalbuildvrt(files[601:900],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_4.vrt")
gdalbuildvrt(files[901:1150],outname)

rm(list=ls())
basefolder<-"Z:/DATA_RAW/MERIT_Hydro/UPSTREAM_DRAINAGE_AREA"
setwd(basefolder)
files<-list.files(basefolder, pattern ='*.tif$', all.files = TRUE, full.names =TRUE, recursive=TRUE)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_1.vrt")
gdalbuildvrt(files[1:300],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_2.vrt")
gdalbuildvrt(files[301:600],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_3.vrt")
gdalbuildvrt(files[601:900],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_4.vrt")
gdalbuildvrt(files[901:1150],outname)


rm(list=ls())
basefolder<-"Z:/DATA_RAW/MERIT_DEM/"
setwd(basefolder)
files<-list.files(basefolder, pattern ='*.tif$', all.files = TRUE, full.names =TRUE, recursive=TRUE)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_1.vrt")
gdalbuildvrt(files[1:300],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_2.vrt")
gdalbuildvrt(files[301:600],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_3.vrt")
gdalbuildvrt(files[601:900],outname)
outname<-paste0("Z:/DATA_RAW/MERIT_Hydro/",basename(basefolder),"_4.vrt")
gdalbuildvrt(files[901:1150],outname)